[duration]
radio_lesson=false
radio_time=false
radio_token=true
spin_time=2
spin_token=500

[error]
check_beep=false
check_correct=true
check_stop=true

[lesson]
combo_theme=
list_open=19
list_own=1
list_training=109
tab_current=0

[main]
check_illustration=false
check_limit_lesson=true
check_open_lesson_warning=false
check_toggle_intelligence=true
language_layout=us_qwerty_win
language_lesson=en_us_qwerty

[mainwindow]
pos=@Point(-1680 0)
size=@Size(1672 1042)

[settings]
current_settings_item=0
ticker_bg_color=#000000
ticker_cursor_color=#176800
ticker_font="Arial,18,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
ticker_font_color=#ffffff
ticker_speed=4

[sound]
check_metronome=false
spin_metronome=60

[support]
check_border=true
check_helpers=true
check_path=true
check_selection=true
check_selection_start=true
check_status=true
